name: 'Get and Cache dependencies'
description:  'Get the dependencies and cache them via npm'
runs: 
  using : 'composite'
  steps:
    - name: Cache Dependencies
      id: cache
      uses: actions/cache@v3
      with:
        path: node_modules
        key: deps-node-modules-${{ hashFiles('**/package-lock.json') }}
    - name: Install Dependencies
      if: steps.cache.outputs.cache-hit != 'true'
      run: npm ci
      shell: bash