name: Reusable Deploy 
on: 
  workflow_call:
    inputs:
      artifact-name: 
        description: "name of the artifacts"
        required: false
        default: "dist-files"
        type: string
    # secrets:
    #   some-secret: 
    #   rquired: false
    outputs:
      result:
        description: "Result of deployment"
        value: ${{ jobs.deploy.outputs.outcome}}
jobs:
  deploy:
    outputs:
      outcome: ${{ steps.result.outputs.step-result }}
    runs-on: ubuntu-latest
    steps:
    - name: Output Information
      run: echo " Deploying & Uploading"
    - name: Get build artifacts
      uses: actions/download-artifact@v3
      with:
        name: ${{ inputs.artifact-name }}
    - name: List Files 
      run: ls
    - name: Result Output
      id: result
      run: echo "::set-output name=step-result::success"